/**
 * Curated emoji library for icon pickers (categories, docs, etc.).
 * Each entry: e = the emoji, n = lowercase search keywords, c = category id.
 * Deliberately sticks to well-established emoji that render everywhere
 * (Windows 10/11, iOS, Android) — no bleeding-edge Unicode.
 */

export type EmojiEntry = { e: string; n: string; c: string };

export const EMOJI_CATEGORIES: { id: string; label: string }[] = [
  { id: "money", label: "💰 Money" },
  { id: "home", label: "🏠 Home" },
  { id: "food", label: "🍽️ Food" },
  { id: "shopping", label: "🛍️ Shopping" },
  { id: "transport", label: "🚗 Transport" },
  { id: "family", label: "🧸 Family" },
  { id: "health", label: "💊 Health" },
  { id: "nature", label: "🐾 Pets & nature" },
  { id: "leisure", label: "🎬 Leisure" },
  { id: "work", label: "💼 Work & tech" },
  { id: "celebrate", label: "🎉 Celebrate" },
  { id: "symbols", label: "⭐ Symbols" },
];

export const EMOJI_LIBRARY: EmojiEntry[] = [
  // ── Money & bills ─────────────────────────────────────────────────────────
  { e: "💰", n: "money bag savings", c: "money" },
  { e: "💵", n: "dollar cash money note", c: "money" },
  { e: "💴", n: "yen cash note", c: "money" },
  { e: "💶", n: "euro cash note", c: "money" },
  { e: "💷", n: "pound cash note", c: "money" },
  { e: "🪙", n: "coin money gold", c: "money" },
  { e: "💳", n: "credit card payment", c: "money" },
  { e: "🧾", n: "receipt bill invoice", c: "money" },
  { e: "🏦", n: "bank fees institution", c: "money" },
  { e: "🏧", n: "atm cash withdrawal", c: "money" },
  { e: "💸", n: "money wings spending loss", c: "money" },
  { e: "📈", n: "chart up growth invest stocks", c: "money" },
  { e: "📉", n: "chart down loss stocks", c: "money" },
  { e: "📊", n: "bar chart budget stats", c: "money" },
  { e: "🧮", n: "abacus calculate accounting", c: "money" },
  { e: "🤑", n: "money face rich", c: "money" },
  { e: "🏷️", n: "label tag price category", c: "money" },
  { e: "💲", n: "dollar sign price", c: "money" },
  { e: "🎰", n: "slot machine gambling lotto", c: "money" },
  { e: "🪪", n: "id card licence", c: "money" },
  // ── Home & utilities ──────────────────────────────────────────────────────
  { e: "🏠", n: "house home", c: "home" },
  { e: "🏡", n: "house garden home", c: "home" },
  { e: "🏢", n: "building office apartment", c: "home" },
  { e: "🏘️", n: "houses neighbourhood", c: "home" },
  { e: "🛋️", n: "couch sofa furniture lounge", c: "home" },
  { e: "🛏️", n: "bed bedroom furniture", c: "home" },
  { e: "🚪", n: "door", c: "home" },
  { e: "🪟", n: "window", c: "home" },
  { e: "🧹", n: "broom cleaning", c: "home" },
  { e: "🧺", n: "basket laundry washing", c: "home" },
  { e: "🧻", n: "toilet paper roll", c: "home" },
  { e: "🧼", n: "soap cleaning wash", c: "home" },
  { e: "🧽", n: "sponge cleaning", c: "home" },
  { e: "🪣", n: "bucket cleaning", c: "home" },
  { e: "🧴", n: "lotion bottle toiletries", c: "home" },
  { e: "🛁", n: "bathtub bathroom", c: "home" },
  { e: "🚿", n: "shower bathroom water", c: "home" },
  { e: "🚽", n: "toilet bathroom plumbing", c: "home" },
  { e: "🔌", n: "plug electricity power utilities", c: "home" },
  { e: "⚡", n: "electricity power energy bolt", c: "home" },
  { e: "💡", n: "light bulb electricity idea", c: "home" },
  { e: "🔋", n: "battery power", c: "home" },
  { e: "💧", n: "water drop utilities", c: "home" },
  { e: "🔥", n: "fire gas heating", c: "home" },
  { e: "🧯", n: "fire extinguisher safety", c: "home" },
  { e: "🪴", n: "plant pot indoor garden", c: "home" },
  { e: "🔧", n: "wrench repair maintenance", c: "home" },
  { e: "🔨", n: "hammer repair diy", c: "home" },
  { e: "🛠️", n: "tools repair maintenance diy", c: "home" },
  { e: "🪛", n: "screwdriver repair diy", c: "home" },
  { e: "🧰", n: "toolbox tools repair", c: "home" },
  { e: "🗑️", n: "bin trash rubbish waste", c: "home" },
  { e: "🔑", n: "key rent lock", c: "home" },
  { e: "🛎️", n: "bell service hotel", c: "home" },
  { e: "🌡️", n: "thermometer heating temperature", c: "home" },
  { e: "❄️", n: "snowflake cooling aircon winter", c: "home" },
  // ── Food & drink ──────────────────────────────────────────────────────────
  { e: "🍽️", n: "plate dining out restaurant", c: "food" },
  { e: "🍳", n: "cooking egg breakfast fry", c: "food" },
  { e: "🥘", n: "pan food paella cooking", c: "food" },
  { e: "🍲", n: "pot stew soup", c: "food" },
  { e: "🥗", n: "salad healthy greens", c: "food" },
  { e: "🍕", n: "pizza takeaway", c: "food" },
  { e: "🍔", n: "burger takeaway fast food", c: "food" },
  { e: "🌭", n: "hot dog sausage bratwurst", c: "food" },
  { e: "🥪", n: "sandwich lunch", c: "food" },
  { e: "🌮", n: "taco mexican", c: "food" },
  { e: "🍜", n: "noodles ramen soup", c: "food" },
  { e: "🍝", n: "spaghetti pasta italian", c: "food" },
  { e: "🍣", n: "sushi japanese", c: "food" },
  { e: "🍤", n: "prawn shrimp seafood", c: "food" },
  { e: "🍚", n: "rice bowl", c: "food" },
  { e: "🍞", n: "bread bakery loaf", c: "food" },
  { e: "🥐", n: "croissant bakery pastry", c: "food" },
  { e: "🥖", n: "baguette bread bakery", c: "food" },
  { e: "🥨", n: "pretzel bakery german", c: "food" },
  { e: "🧀", n: "cheese dairy", c: "food" },
  { e: "🥚", n: "egg dairy", c: "food" },
  { e: "🥩", n: "steak meat butcher", c: "food" },
  { e: "🥓", n: "bacon meat breakfast", c: "food" },
  { e: "🍗", n: "chicken poultry meat", c: "food" },
  { e: "🍖", n: "meat bone bbq", c: "food" },
  { e: "🥦", n: "broccoli vegetables", c: "food" },
  { e: "🥕", n: "carrot vegetables", c: "food" },
  { e: "🌽", n: "corn vegetables", c: "food" },
  { e: "🍅", n: "tomato vegetables", c: "food" },
  { e: "🥑", n: "avocado fruit", c: "food" },
  { e: "🍎", n: "apple fruit", c: "food" },
  { e: "🍌", n: "banana fruit", c: "food" },
  { e: "🍇", n: "grapes fruit", c: "food" },
  { e: "🍓", n: "strawberry fruit berries", c: "food" },
  { e: "🍉", n: "watermelon fruit", c: "food" },
  { e: "🍊", n: "orange fruit citrus", c: "food" },
  { e: "🍋", n: "lemon fruit citrus", c: "food" },
  { e: "🎂", n: "birthday cake celebration", c: "food" },
  { e: "🧁", n: "cupcake sweets baking", c: "food" },
  { e: "🍪", n: "cookie biscuit sweets", c: "food" },
  { e: "🍩", n: "donut sweets", c: "food" },
  { e: "🍫", n: "chocolate sweets", c: "food" },
  { e: "🍬", n: "candy lollies sweets", c: "food" },
  { e: "🍦", n: "ice cream dessert", c: "food" },
  { e: "☕", n: "coffee cafe tea hot drink", c: "food" },
  { e: "🍵", n: "tea green matcha", c: "food" },
  { e: "🧃", n: "juice box drink kids", c: "food" },
  { e: "🥤", n: "soft drink cup soda", c: "food" },
  { e: "🍺", n: "beer pub alcohol", c: "food" },
  { e: "🍷", n: "wine alcohol", c: "food" },
  { e: "🥂", n: "champagne cheers celebration", c: "food" },
  { e: "🍸", n: "cocktail bar alcohol", c: "food" },
  { e: "🥛", n: "milk dairy glass", c: "food" },
  { e: "🍯", n: "honey jar", c: "food" },
  // ── Shopping & clothing ───────────────────────────────────────────────────
  { e: "🛒", n: "shopping cart trolley groceries supermarket", c: "shopping" },
  { e: "🛍️", n: "shopping bags retail", c: "shopping" },
  { e: "👕", n: "tshirt clothing clothes", c: "shopping" },
  { e: "👖", n: "jeans pants clothing", c: "shopping" },
  { e: "👗", n: "dress clothing", c: "shopping" },
  { e: "🧥", n: "coat jacket clothing", c: "shopping" },
  { e: "🧦", n: "socks clothing", c: "shopping" },
  { e: "🧤", n: "gloves clothing winter", c: "shopping" },
  { e: "🧣", n: "scarf clothing winter", c: "shopping" },
  { e: "👟", n: "sneakers shoes runners", c: "shopping" },
  { e: "👞", n: "shoes dress formal", c: "shopping" },
  { e: "👠", n: "heels shoes", c: "shopping" },
  { e: "🥾", n: "boots hiking shoes", c: "shopping" },
  { e: "👜", n: "handbag bag", c: "shopping" },
  { e: "👛", n: "purse wallet", c: "shopping" },
  { e: "🎒", n: "backpack school bag", c: "shopping" },
  { e: "👓", n: "glasses eyewear optometrist", c: "shopping" },
  { e: "🕶️", n: "sunglasses eyewear", c: "shopping" },
  { e: "💍", n: "ring jewellery wedding", c: "shopping" },
  { e: "⌚", n: "watch time jewellery", c: "shopping" },
  { e: "💄", n: "lipstick makeup beauty", c: "shopping" },
  { e: "🧢", n: "cap hat clothing", c: "shopping" },
  { e: "👒", n: "hat sun clothing", c: "shopping" },
  // ── Transport ─────────────────────────────────────────────────────────────
  { e: "🚗", n: "car transport drive", c: "transport" },
  { e: "🚙", n: "suv car transport", c: "transport" },
  { e: "🚕", n: "taxi uber cab", c: "transport" },
  { e: "🚌", n: "bus public transport", c: "transport" },
  { e: "🏎️", n: "race car fast", c: "transport" },
  { e: "🛻", n: "ute pickup truck", c: "transport" },
  { e: "🚚", n: "truck delivery removal", c: "transport" },
  { e: "🚜", n: "tractor farm", c: "transport" },
  { e: "🏍️", n: "motorbike motorcycle", c: "transport" },
  { e: "🛵", n: "scooter moped", c: "transport" },
  { e: "🚲", n: "bicycle bike cycling", c: "transport" },
  { e: "🛴", n: "kick scooter", c: "transport" },
  { e: "🚂", n: "train steam locomotive", c: "transport" },
  { e: "🚆", n: "train rail public transport", c: "transport" },
  { e: "🚇", n: "metro subway underground", c: "transport" },
  { e: "✈️", n: "plane flight travel holidays", c: "transport" },
  { e: "🛫", n: "plane departure takeoff", c: "transport" },
  { e: "🚀", n: "rocket space launch", c: "transport" },
  { e: "⛵", n: "sailboat sailing", c: "transport" },
  { e: "🚤", n: "speedboat boat", c: "transport" },
  { e: "🚢", n: "ship cruise ferry", c: "transport" },
  { e: "⛽", n: "fuel petrol gas station", c: "transport" },
  { e: "🅿️", n: "parking", c: "transport" },
  { e: "🚦", n: "traffic light", c: "transport" },
  { e: "🛞", n: "tyre wheel car service", c: "transport" },
  { e: "🧳", n: "luggage suitcase travel", c: "transport" },
  { e: "🚐", n: "van campervan caravan", c: "transport" },
  // ── Family & kids ─────────────────────────────────────────────────────────
  { e: "👶", n: "baby infant", c: "family" },
  { e: "🧒", n: "child kid", c: "family" },
  { e: "👦", n: "boy kid", c: "family" },
  { e: "👧", n: "girl kid", c: "family" },
  { e: "👨", n: "man dad father", c: "family" },
  { e: "👩", n: "woman mum mother", c: "family" },
  { e: "👴", n: "grandpa old man", c: "family" },
  { e: "👵", n: "grandma old woman", c: "family" },
  { e: "👪", n: "family parents kids", c: "family" },
  { e: "🍼", n: "baby bottle milk", c: "family" },
  { e: "🧸", n: "teddy bear toys kids", c: "family" },
  { e: "🪆", n: "nesting dolls toys", c: "family" },
  { e: "🎠", n: "carousel fair kids", c: "family" },
  { e: "🧩", n: "puzzle piece games kids", c: "family" },
  { e: "🪁", n: "kite outdoors kids", c: "family" },
  { e: "📚", n: "books school reading", c: "family" },
  { e: "✏️", n: "pencil school stationery", c: "family" },
  { e: "🖍️", n: "crayon kids art", c: "family" },
  { e: "🎨", n: "art palette painting craft", c: "family" },
  { e: "🎓", n: "graduation school university education", c: "family" },
  { e: "🏫", n: "school building education", c: "family" },
  { e: "💑", n: "couple love date", c: "family" },
  // ── Health & self-care ────────────────────────────────────────────────────
  { e: "🏥", n: "hospital medical doctor", c: "health" },
  { e: "💊", n: "pill medicine pharmacy chemist", c: "health" },
  { e: "💉", n: "syringe vaccine injection", c: "health" },
  { e: "🩹", n: "bandaid plaster first aid", c: "health" },
  { e: "🩺", n: "stethoscope doctor gp", c: "health" },
  { e: "🦷", n: "tooth dentist dental", c: "health" },
  { e: "🧠", n: "brain mental health", c: "health" },
  { e: "🫀", n: "heart organ cardio", c: "health" },
  { e: "🏃", n: "running exercise fitness", c: "health" },
  { e: "🧘", n: "yoga meditation wellness", c: "health" },
  { e: "🛌", n: "sleep rest bed", c: "health" },
  { e: "😷", n: "mask sick ill", c: "health" },
  { e: "🤒", n: "sick fever thermometer", c: "health" },
  { e: "🪥", n: "toothbrush dental hygiene", c: "health" },
  { e: "💆", n: "massage spa relax", c: "health" },
  { e: "💇", n: "haircut hairdresser barber", c: "health" },
  { e: "✂️", n: "scissors cut hairdresser", c: "health" },
  { e: "💅", n: "nails manicure beauty", c: "health" },
  { e: "🧖", n: "sauna spa steam", c: "health" },
  // ── Pets & nature ─────────────────────────────────────────────────────────
  { e: "🐾", n: "paw prints pets animals", c: "nature" },
  { e: "🐕", n: "dog pet", c: "nature" },
  { e: "🐈", n: "cat pet", c: "nature" },
  { e: "🐇", n: "rabbit bunny pet", c: "nature" },
  { e: "🐹", n: "hamster pet", c: "nature" },
  { e: "🐢", n: "turtle pet", c: "nature" },
  { e: "🐠", n: "fish aquarium pet", c: "nature" },
  { e: "🐦", n: "bird pet", c: "nature" },
  { e: "🦜", n: "parrot bird pet", c: "nature" },
  { e: "🐍", n: "snake reptile pet", c: "nature" },
  { e: "🐴", n: "horse riding", c: "nature" },
  { e: "🐄", n: "cow farm cattle", c: "nature" },
  { e: "🐖", n: "pig pork farm", c: "nature" },
  { e: "🐑", n: "sheep lamb farm wool", c: "nature" },
  { e: "🐓", n: "rooster chicken farm", c: "nature" },
  { e: "🌳", n: "tree garden park", c: "nature" },
  { e: "🌲", n: "pine tree forest", c: "nature" },
  { e: "🌵", n: "cactus plant", c: "nature" },
  { e: "🌷", n: "tulip flower garden", c: "nature" },
  { e: "🌹", n: "rose flower florist", c: "nature" },
  { e: "🌻", n: "sunflower flower", c: "nature" },
  { e: "💐", n: "bouquet flowers florist gift", c: "nature" },
  { e: "🍀", n: "clover luck", c: "nature" },
  { e: "🌱", n: "seedling plant garden grow", c: "nature" },
  { e: "⛰️", n: "mountain hiking outdoors", c: "nature" },
  { e: "🏞️", n: "park nature landscape", c: "nature" },
  { e: "🌊", n: "wave ocean sea beach", c: "nature" },
  { e: "☀️", n: "sun sunny weather", c: "nature" },
  { e: "🌧️", n: "rain weather", c: "nature" },
  { e: "🌈", n: "rainbow weather", c: "nature" },
  // ── Leisure, sport & travel ───────────────────────────────────────────────
  { e: "🎬", n: "movies cinema film entertainment", c: "leisure" },
  { e: "📺", n: "tv television streaming subscriptions", c: "leisure" },
  { e: "🎮", n: "gaming video games controller", c: "leisure" },
  { e: "🕹️", n: "joystick arcade games", c: "leisure" },
  { e: "🎲", n: "dice board games", c: "leisure" },
  { e: "♟️", n: "chess board games", c: "leisure" },
  { e: "🎳", n: "bowling", c: "leisure" },
  { e: "🎯", n: "darts target", c: "leisure" },
  { e: "🎱", n: "pool billiards", c: "leisure" },
  { e: "🎤", n: "microphone karaoke concert", c: "leisure" },
  { e: "🎧", n: "headphones music", c: "leisure" },
  { e: "🎼", n: "music score sheet", c: "leisure" },
  { e: "🎹", n: "piano keyboard music lessons", c: "leisure" },
  { e: "🎸", n: "guitar music lessons", c: "leisure" },
  { e: "🥁", n: "drums music", c: "leisure" },
  { e: "🎻", n: "violin music lessons", c: "leisure" },
  { e: "🎭", n: "theatre performing arts", c: "leisure" },
  { e: "🎪", n: "circus tent show", c: "leisure" },
  { e: "🎡", n: "ferris wheel fair", c: "leisure" },
  { e: "🎢", n: "rollercoaster theme park", c: "leisure" },
  { e: "🏖️", n: "beach holiday umbrella", c: "leisure" },
  { e: "🏝️", n: "island holiday tropical", c: "leisure" },
  { e: "⛺", n: "tent camping", c: "leisure" },
  { e: "🏕️", n: "camping campsite", c: "leisure" },
  { e: "🗺️", n: "map travel", c: "leisure" },
  { e: "🧭", n: "compass navigation adventure", c: "leisure" },
  { e: "🎣", n: "fishing rod", c: "leisure" },
  { e: "⚽", n: "soccer football sport", c: "leisure" },
  { e: "🏀", n: "basketball sport", c: "leisure" },
  { e: "🏈", n: "football nfl sport", c: "leisure" },
  { e: "🏉", n: "rugby league sport", c: "leisure" },
  { e: "⚾", n: "baseball sport", c: "leisure" },
  { e: "🎾", n: "tennis sport", c: "leisure" },
  { e: "🏐", n: "volleyball sport", c: "leisure" },
  { e: "🏏", n: "cricket sport", c: "leisure" },
  { e: "🥊", n: "boxing gloves sport", c: "leisure" },
  { e: "⛳", n: "golf flag sport", c: "leisure" },
  { e: "🏊", n: "swimming pool sport", c: "leisure" },
  { e: "🏄", n: "surfing beach sport", c: "leisure" },
  { e: "🚴", n: "cycling bike sport", c: "leisure" },
  { e: "🏋️", n: "gym weights fitness", c: "leisure" },
  { e: "⛷️", n: "skiing snow sport", c: "leisure" },
  { e: "🏂", n: "snowboarding snow sport", c: "leisure" },
  { e: "🧗", n: "climbing bouldering sport", c: "leisure" },
  { e: "🛶", n: "canoe kayak paddle", c: "leisure" },
  // ── Work, school & tech ───────────────────────────────────────────────────
  { e: "💼", n: "briefcase work business salary", c: "work" },
  { e: "🖥️", n: "desktop computer tech", c: "work" },
  { e: "💻", n: "laptop computer tech", c: "work" },
  { e: "⌨️", n: "keyboard tech", c: "work" },
  { e: "🖱️", n: "mouse computer tech", c: "work" },
  { e: "🖨️", n: "printer office", c: "work" },
  { e: "📱", n: "phone mobile internet", c: "work" },
  { e: "☎️", n: "telephone landline", c: "work" },
  { e: "📡", n: "satellite internet nbn", c: "work" },
  { e: "📧", n: "email mail", c: "work" },
  { e: "📮", n: "postbox mail postage", c: "work" },
  { e: "📦", n: "package parcel delivery post", c: "work" },
  { e: "📝", n: "memo note writing", c: "work" },
  { e: "📄", n: "document page paper", c: "work" },
  { e: "📑", n: "tabs document pages", c: "work" },
  { e: "📅", n: "calendar date schedule", c: "work" },
  { e: "🗂️", n: "dividers files organise", c: "work" },
  { e: "📁", n: "folder files", c: "work" },
  { e: "📌", n: "pin location note", c: "work" },
  { e: "📎", n: "paperclip attach", c: "work" },
  { e: "📏", n: "ruler measure", c: "work" },
  { e: "🖊️", n: "pen writing stationery", c: "work" },
  { e: "🔒", n: "lock security insurance", c: "work" },
  { e: "🛡️", n: "shield insurance protection", c: "work" },
  { e: "🏭", n: "factory industry", c: "work" },
  { e: "⚙️", n: "gear settings machine", c: "work" },
  { e: "🧪", n: "test tube science lab", c: "work" },
  { e: "🔬", n: "microscope science lab", c: "work" },
  { e: "🔭", n: "telescope astronomy", c: "work" },
  { e: "⚖️", n: "scales legal lawyer justice", c: "work" },
  { e: "🧑‍💻", n: "developer coding programmer", c: "work" },
  // ── Celebrations & gifts ──────────────────────────────────────────────────
  { e: "🎉", n: "party popper celebration", c: "celebrate" },
  { e: "🎊", n: "confetti celebration", c: "celebrate" },
  { e: "🎁", n: "gift present birthday christmas", c: "celebrate" },
  { e: "🎈", n: "balloon party birthday", c: "celebrate" },
  { e: "🎄", n: "christmas tree holidays", c: "celebrate" },
  { e: "🎃", n: "halloween pumpkin", c: "celebrate" },
  { e: "🎆", n: "fireworks new year", c: "celebrate" },
  { e: "✨", n: "sparkles special magic", c: "celebrate" },
  { e: "🎀", n: "ribbon bow gift", c: "celebrate" },
  { e: "🥳", n: "party face celebration", c: "celebrate" },
  { e: "💝", n: "heart gift valentine", c: "celebrate" },
  { e: "❤️", n: "red heart love", c: "celebrate" },
  { e: "💚", n: "green heart", c: "celebrate" },
  { e: "💙", n: "blue heart", c: "celebrate" },
  { e: "💜", n: "purple heart", c: "celebrate" },
  { e: "💛", n: "yellow heart", c: "celebrate" },
  { e: "🧡", n: "orange heart", c: "celebrate" },
  // ── Symbols ───────────────────────────────────────────────────────────────
  { e: "⭐", n: "star favourite", c: "symbols" },
  { e: "🌟", n: "glowing star special", c: "symbols" },
  { e: "✅", n: "check tick done", c: "symbols" },
  { e: "❌", n: "cross no cancel", c: "symbols" },
  { e: "❗", n: "exclamation important", c: "symbols" },
  { e: "❓", n: "question unknown", c: "symbols" },
  { e: "⚠️", n: "warning caution", c: "symbols" },
  { e: "🚫", n: "prohibited no banned", c: "symbols" },
  { e: "♻️", n: "recycle green environment", c: "symbols" },
  { e: "🔴", n: "red circle", c: "symbols" },
  { e: "🟠", n: "orange circle", c: "symbols" },
  { e: "🟡", n: "yellow circle", c: "symbols" },
  { e: "🟢", n: "green circle", c: "symbols" },
  { e: "🔵", n: "blue circle", c: "symbols" },
  { e: "🟣", n: "purple circle", c: "symbols" },
  { e: "🔶", n: "orange diamond", c: "symbols" },
  { e: "🔷", n: "blue diamond", c: "symbols" },
  { e: "🔔", n: "bell notification reminder", c: "symbols" },
  { e: "📢", n: "megaphone announcement", c: "symbols" },
  { e: "💤", n: "sleep zzz", c: "symbols" },
  { e: "🏁", n: "chequered flag finish", c: "symbols" },
  { e: "🇦🇺", n: "australia flag", c: "symbols" },
  { e: "🇩🇪", n: "germany flag german", c: "symbols" },
];
